namespace Betalgo.Blueflow.OpenAPIToCode.Generators.Models
{
    /// <summary>
    ///     Default implementation of ICodeGeneratorConfiguration for C# code generation.
    /// </summary>
    public class CSharpCodeGeneratorConfiguration : ICodeGeneratorConfiguration
    {
        /// <summary>
        ///     Example property: Whether to use tabs for indentation.
        /// </summary>
        public bool UseTabs { get; set; } = false;

        /// <summary>
        ///     Example property: File header to include in generated files.
        /// </summary>
        public string FileHeader { get; set; } = "// Generated by Blueflow";

        public string? ClassNamePrefix { get; set; } 
        public string? ClassNameSuffix { get; set; }
        public string? DocumentationBaseDomain { get; set; }
        = "https://platform.openai.com";
    }
}
